name: Build Kernel on AzureLinux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azurelinux/base/core:3.0
    steps:

      - name: Install build dependencies
        run: |
          tdnf install -y --nogpgcheck tar audit-devel build-essential cpio diffutils dwarv

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: rolling-lts/mariner-3/6.6.88.1

      - name: Download kernel config
        run: |
          wget https://raw.githubusercontent.com/microsoft/azurelinux/3.0-dev/SPECS/kernel/config
          cp config .config

      - name: Prepare kernel config
        run: make oldconfig || true

      - name: Build kernel
        run: make -j$(nproc)
